// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCni-S-3KOkR1rGhp4uj-cXgkvJkWiTOSg',
    appId: '1:525015118563:web:b537aaae0e80b841d50bd6',
    messagingSenderId: '525015118563',
    projectId: 'first-b0a9b',
    authDomain: 'first-b0a9b.firebaseapp.com',
    storageBucket: 'first-b0a9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6DrwC252Jr6J_AbROlxerLszeUFatmhc',
    appId: '1:525015118563:android:972ef01d890840cbd50bd6',
    messagingSenderId: '525015118563',
    projectId: 'first-b0a9b',
    storageBucket: 'first-b0a9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRYsEPDI1yW-OxDHmzaUYg9ujbbewNk-8',
    appId: '1:525015118563:ios:df400032d5b979f7d50bd6',
    messagingSenderId: '525015118563',
    projectId: 'first-b0a9b',
    storageBucket: 'first-b0a9b.appspot.com',
    iosBundleId: 'com.example.fourthpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRYsEPDI1yW-OxDHmzaUYg9ujbbewNk-8',
    appId: '1:525015118563:ios:f22ae6d50e76f6b9d50bd6',
    messagingSenderId: '525015118563',
    projectId: 'first-b0a9b',
    storageBucket: 'first-b0a9b.appspot.com',
    iosBundleId: 'com.example.fourthpro.RunnerTests',
  );
}
